### ISSUE TITLE
Missing assets 

### ISSUE THREAD

**Issue by pingpongcat** [lcthums/C3D#1]
I compile it but this likes stopped me:

mesh* floor = mesh_genFlatFloor(16, "res/textures/grass.jpg");
linkedList* meshList = list_create();
	mesh_loadFromFileToList("res/obj/raptor.obj", "res/textures/raptor.png", meshList);
font* font = font_load(12, 16, "res/fonts/pixfont.jpg");

Could you add those files ? or they are protected with some licence ? I'm really interested how this engine work :)

**Comment by thumsl** [comment]
I've added a few public domain assets so you can test the included example, but there is nothing specific about them, you can use any .obj model for trying the engine out. The included model's texture is inverted in-game, not sure what's going on there but I didn't feel like figuring it out either.

The included example now showcases point lights and the "level generator", you can check out the bitmap file that defines the level inside the res directory. 

I've also added to the readme file a link to a youtube playlist with a couple of videos about the engine
